import Header from "@/components/header";
import "./globals.css";
import Footer from "@/components/footer";
import '../scss/main.scss';
import SmoothScroll from "@/components/SmoothScroll";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>
          <Header />
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
